### ISSUE TITLE
Python 3.8 compatibility

### ISSUE THREAD

**Issue by yochananmarqos** [cloudlinux/kcare-uchecker#6]
I read that the `platform.linux_distribution` function was removed
in Python 3.8. Can compatibility be added?

```
Traceback (most recent call last):
  File "/usr/sbin/uchecker", line 33, in <module>
    sys.exit(load_entry_point('kcare-uchecker==0.1.0b1', 'console_scripts', 'uchecker')())
  File "/usr/sbin/uchecker", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/uchecker.py", line 59, in <module>
    DIST, _, _ = platform.linux_distribution()
AttributeError: module 'platform' has no attribute 'linux_distribution'
```

**Comment by histrio** [comment]
Thanks, @yochananmarqos !
